name: CI
on:
  pull_request:
    paths:
      - "src/**"
      - ".eslint*"
      - ".github/workflows/ci.yml"

jobs:
  # Linting and type checking
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "yarn"

      - name: Cache eslint
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.eslintcache
          key: ${{ runner.os }}-eslint-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*.ts') }}
          restore-keys: |
            ${{ runner.os }}-eslint-

      - name: Install dependencies
        run: |
          # Main app
          yarn install

      - name: Build app
        run: |
          # Main app
          yarn build
        env:
          CI: true

      - name: Lint and Type-check
        run: |
          # Linting
          yarn lint

          # Typescript type checks
          yarn type-check

          # TODO: tests
        env:
          CI: true
