name: CI
on:
  pull_request:
    paths:
      - "packages/**"
      - ".eslint*"
      - ".github/workflows/ci.yml"

jobs:
  # Linting and type checking
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enable corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Cache eslint
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.eslintcache
          key: ${{ runner.os }}-eslint-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.ts') }}
          restore-keys: |
            ${{ runner.os }}-eslint-

      - name: Install dependencies
        run: |
          # Main app
          pnpm install

      - name: Build app
        run: |
          # Main app
          pnpm build
        env:
          CI: true

      - name: Lint and Type-check
        run: |
          # Linting
          pnpm lint

          # Typescript type checks
          pnpm type-check

          # TODO: tests
        env:
          CI: true
