name: "Edge: deploy to NPM"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Publish to NPM
    if: ${{ github.ref == 'refs/heads/main' }}

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build & Publish
        run: |
          if [ ! -v NPM_TOKEN ]; then echo "NPM_TOKEN not set"; exit 1; fi;
          npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
          yarn install
          yarn build
          cd packages/shared/edge-utils
          npm publish
