name: Debug NPM Deploy

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Publish to NPM
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build & Publish
        run: |
          yarn install
          yarn build
          ls -lah dist